### ISSUE TITLE
Feature Request: Automated Issue Management for Backlog Project

### ISSUE THREAD

**Issue by tammyyang** [numbersprotocol/capture-lite#3330]
# Feature Request: Automated Issue Management for Backlog Project

## Summary
Implement a GitHub Action workflow to `capture-lite` and `storage-backend` repositories automatically add newly created issues to the Numbers Protocol Backlog project.

## Description
This feature will streamline issue management by ensuring all new issues are automatically added to our Backlog project board without manual intervention.

## Implementation Details
A GitHub Actions workflow will be created.

## Code Implementation
The workflow will be implemented using the following YAML configuration:

```yaml
name: Add Issues to Backlog Project
on:
  issues:
    types:
      - opened
jobs:
  add-to-project:
    name: Add issue to Backlog project
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to Backlog project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/numbersprotocol/projects/8
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
```

## Prerequisites
1. Create a Personal Access Token (PAT) with appropriate permissions
2. Add the token as a repository secret named `ADD_TO_PROJECT_PAT`
